# Generated by Django 4.1.1 on 2022-09-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publishing_house',
            new_name='PublishingHouse',
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_date',
            field=models.DateField(null=True),
        ),
    ]
