# Generated by Django 4.1.1 on 2022-09-24 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0002_rename_publishing_house_publishinghouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='adding_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
