# Generated by Django 4.1.1 on 2022-09-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0003_book_adding_date_book_is_borrowed_book_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sys_number',
            field=models.CharField(default=11111111, max_length=8),
            preserve_default=False,
        ),
    ]
