# Generated by Django 4.1.1 on 2022-09-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0004_book_sys_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sys_number',
        ),
    ]
