# Generated by Django 4.1.1 on 2022-09-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0005_remove_book_sys_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publishing_date',
        ),
        migrations.AddField(
            model_name='book',
            name='publishing_year',
            field=models.IntegerField(null=True),
        ),
    ]
