# Generated by Django 4.1.1 on 2022-09-29 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_library', '0006_remove_book_publishing_date_book_publishing_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('bor_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bor_books', to='my_library.book')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('user_id', models.UUIDField(default=uuid.UUID('a538f54f-6e95-458e-b5ac-45cd5dd308b9'), editable=False, unique=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('borrowed_books', models.ManyToManyField(null=True, related_name='borrowed_books', through='my_library.BorrowedBooks', to='my_library.book')),
                ('django_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_date', models.DateField(auto_now_add=True)),
                ('res_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='res_books', to='my_library.book')),
                ('res_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='res_users', to='my_library.libraryuser')),
            ],
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='reserved_books',
            field=models.ManyToManyField(null=True, related_name='reserved_books', through='my_library.ReservedBooks', to='my_library.book'),
        ),
        migrations.AddField(
            model_name='borrowedbooks',
            name='bor_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bor_users', to='my_library.libraryuser'),
        ),
    ]
